### ISSUE TITLE
Erro na CA sem armadura

### ISSUE THREAD

**Issue by Uxxus** [pedroleone/ose-srd#15]
https://ose-srd.netlify.app/personagens/2-criando-personagem

Onde diz: 
"CA Sem Armadura Se o seu personagem não tem armadura, sua CA base é 9 [0]." 

Deveria dizer: 
"CA Sem Armadura Se o seu personagem não tem armadura, sua CA base é 9 [10].

**Comment by nerun** [comment]
Corrigido, obrigado. Pode não aparecer corrigido imediatamente no site. Pode levar 1 semana.
