### ISSUE TITLE
Modificadores de Força

### ISSUE THREAD

**Issue by Uxxus** [pedroleone/ose-srd#16]
https://ose-srd.netlify.app/personagens/3-atributos

Na tabela de "Força (FOR) - Modificadores de Força", os valores 16-17 estão com bônus +1, o correto é +2

**Comment by nerun** [comment]
Corrigido, obrigado.

Sabedoria e Constituição também estavam errados. Corrigido.

Não vai aparecer corrigido no site tão rapidamente, pode levar 1 semana.

**Comment by Uxxus** [comment]
> Corrigido, obrigado.
> 
> Sabedoria e Constituição também estavam errados. Corrigido.
> 
> Não vai aparecer corrigido no site tão rapidamente, pode levar 1 semana.

Obrigado, o 4-5 de Força também estava incorreto.

**Comment by nerun** [comment]
Putz! Mais um... vou corrigir.
